### PR TITLE
Upgrade alpine to 3.18

### PR DESCRIPTION
**Pull request by xbglowx**

### CODE REVIEW

**Comment by cageyv** [comment]
@martinhaus Could we possibly merge this? Would really appreciate your input

**Comment by MarkDPierce** [comment]
This project is legit dead.

**Comment by cageyv** [comment]
@MarkDPierce any alternatives?
The main problem "Cloudflare Metrics -> Prometheus" is still exists

**Comment by MarkDPierce** [comment]
> @MarkDPierce any alternatives? The main problem "Cloudflare Metrics -> Prometheus" is still exists

Fork the project and update your fork to use alpine and build the image. 

The problem is when cloudflare adjusts their APIs or make changes that are not reflected in this code base because its dead. We have not bothered finding an alternative because we are pulling metrics a different way and the metrics provided by this repo are not what we are after. I totally get it for smaller websites and such though.

**Comment by cageyv** [comment]
> we are pulling metrics a different way

@MarkDPierce any suggestions or at least some key words?
My case is also not small one and it is why I actually need metrics in prometheus. For small projects Cloudflare itself is good enough. 

- (Blog post)[https://blog.cloudflare.com/improving-your-monitoring-setup-by-integrating-cloudflares-analytics-data-- into-prometheus-and-grafana/] points to that repo 
- https://github.com/transferwise/cloudflare-prometheus-exporter use similar solution 
- https://gitlab.com/gitlab-org/cloudflare_exporter moved to that repo

**Pull request merged**
