### PR TITLE
Fix identation for serviceMonitor.labels

### PR DESCRIPTION
**Pull request by commixon**
This is a real simple fix for the identation of `.Values.serviceMonitor.labels`.

Previously, with the following `values.yaml` it produces an error in identation:
```yaml
serviceMonitor:
  # Whether to create service account
  enabled: true
  labels:
    foo: bar
```

```bash
# Source: cloudflare-exporter/templates/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    helm.sh/chart: cloudflare-exporter-0.1.1
    app.kubernetes.io/name: cloudflare-exporter
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.6"
    app.kubernetes.io/managed-by: Helm
        foo: bar
  name: RELEASE-NAME-cloudflare-exporter
...
 not allowed in this context
helm.go:81: [debug] error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
YAML parse error on cloudflare-exporter/templates/servicemonitor.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:240
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newTemplateCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

```

### CODE REVIEW

**Comment by martinhaus** [comment]
@commixon Can you also bump chart version?

**Comment by commixon** [comment]
@martinhaus I see the tests are failing on the installation step. As far as I can understand there are no nodes available? Is this specific to this PR, do you think I should add something here?

**Comment by martinhaus** [comment]
@commixon This is unrelated to your PR. It was a problem with the Github action that we're using for testing helm charts.
I've bumped the version in master, which fixes this problem. Could you rebase your branch and try this again? 

It should work smoothly, I'll merge the PR after that.

**Comment by martinhaus** [comment]
Perfect, thanks for this!

**Pull request merged**
